### ISSUE TITLE
Load a script directly instead of waiting for polyfills?

### ISSUE THREAD

**Issue by sarahsturgeon** [bfanger/tvkit#14]
I need to display my sveltekit app on a very old Chrome version. This tool works where no others did, so thank you!

With tvkit, it seems like the scripts run a little after the page fully loads, presumably as a way to ensure that the polyfills are loaded before the scripts run.

However, I need some of my (already-compatible) javascript to run immediately where I put my `<script>` tag.

Is there any way to do this?

**Comment by bfanger** [comment]
Not yet, i'm thinking about adding support for a `data-tvkit="ignore"` attribute for script tags

**Comment by sarahsturgeon** [comment]
That would do the trick 👍
