### ISSUE TITLE
Server code not getting transpiled

### ISSUE THREAD

**Issue by christowiz** [bfanger/tvkit#16]
The HTML that is served from the server contains Promises and arrow functions as text template when running a build.  This doesn't gets skipped during the TVKit build process and throws an error on ES5 devices.  I see that `import()` is changed to `System.import()` when passing the `--add es-module`.

It tried adding `--add es-module,arrow-functions` which was logged during the beginning of the build but didn't transpile the string template code.
<img src="https://github.com/bfanger/tvkit/assets/597282/28cc1664-6927-4755-927a-038ea19c2f8a" width="600">

HTML source:
<img src="https://github.com/bfanger/tvkit/assets/597282/622d1cbb-66fe-4bf1-95de-d953d9068795" width="500">

Built code from TVKit
<img src="https://github.com/bfanger/tvkit/assets/597282/646217cb-b41a-4f1d-ab51-bc352443da53" width="500">

**Comment by bfanger** [comment]
Some javascript is generated at runtime by adapter-node, I've updated the patches for SvelteKit v2.

**Comment by christowiz** [comment]
@bfanger Awesome!  Thanks for quick response. 
There are other issues with the output though to be ES5 supported.  Here is the current output still missing a couple items
![image](https://github.com/bfanger/tvkit/assets/597282/61be0fad-022a-46e6-b395-2380144df7f6)

**Comment by bfanger** [comment]
These should be fixed in 0.16.1

Thanks for reporting the issue.

**Comment by christowiz** [comment]
> These should be fixed in 0.16.1
> 
> Thanks for reporting the issue.

@bfanger Thanks for the fixes and the great project.
