### ISSUE TITLE
SsytemJS error when transpiling static build using Vite static adapter

### ISSUE THREAD

**Issue by christowiz** [bfanger/tvkit#17]
The Sveltekit static adapter build runs successfully but fails when running a tvkit build on the static output.

![image](https://github.com/bfanger/tvkit/assets/597282/b9092904-a660-44b5-870c-67aeb22b8adb)

And here is what seems the relevant origin point of the trace
![image](https://github.com/bfanger/tvkit/assets/597282/56b74d95-adb1-46d9-81eb-a25046ec01cf)

Here is a direct link to the logged SystemJS error #8
https://github.com/systemjs/systemjs/blob/main/docs/errors.md#8

**Comment by bfanger** [comment]
I couldn't reproduce this bug.

I've tried the sveltekit demo `npm create svelte@latest my-app` then removed sverdle and changed the adapter to adapter-static.
```sh
npx tvkit@latest build --browser chrome38 ./build  -o dist
npx serve@latest ./dist
```
and it worked fine, looks like something in your codebase is triggering this bug.

Could you provide a code example based on SvelteKit demo that is triggers this issue?

**Comment by christowiz** [comment]
@bfanger Thanks for the info.  I'll do some exploration on my side.  I hadn't been able to get it work since we started this project but it sounds like something in the way the site or dependencies are set up.  I'll close this for now as you are most likely correct. Thanks.
